# Nba Regular Season 2018-19 Data Challenge

Your task will be to take the dataset given, and create an analysis answering the following 10 questions. This project will again test your knowledge of pandas in order to find the answers needed given the data you are presented with.

# What was the average age of player in the league?

In [19]:
import pandas as pd
import numpy as np
nba_data = pd.read_csv('nbastats2018-2019.csv', sep = ',')
average_age = nba_data['Age'].mean()
print(f"The average age of a player was {average_age} in 2018-19")

The average age of a player was 25.900191938579656 in 2018-19

# What player scored the most points?

In [2]:
most_points = nba_data.sort_values('Points', kind = 'mergesort', ascending = False).reset_index()
most_points.loc[0][['Name', 'Points']]

Name      James Harden
Points            36.1
Name: 0, dtype: object

# What player had the most blocks during the season? Was it a post player (F/C)?

In [3]:
most_blocks = nba_data.sort_values('Blocks', ascending = False).reset_index()
most_blocks.loc[0][['Name', 'Blocks']]

#  I dont see player positions in the data but according to google, he is a center

Name      Myles Turner
Blocks             2.7
Name: 0, dtype: object

# Based on the regular season, who had the best chance to win a title given their win percentage?

In [4]:
best_ws48 = nba_data[nba_data['MP'] > 20].sort_values('WS48', ascending = False).reset_index()
best_ws48.loc[0][['Name', 'MP', 'WS48']]

# Zhou Qi has the best WS48 which tells a player's win share per 48 minutes.  But, with only 1
# minute played per game, Qi was not as impactful as this stat implies.  I narrowed the query to
# only include players who average atleast 20 minutes a game as they are the ones that are going 
# to influence the outcome of games more

Name    Giannis Antetokounmpo
MP                       32.8
WS48                    0.292
Name: 0, dtype: object

# What player had the best 3-pt percentage?

In [5]:
best_3fg = nba_data[(nba_data['G'] > 50) & (nba_data['MP'] > 20)].sort_values('FG3%', ascending = False).reset_index()
best_3fg[['Name', 'Team', 'G', 'MP', 'FG3%', 'FGA']]

# Out of all of the players that played in atleast 50 games and played an average of atleast 20 minutes per game,
# Domantas Sabonis had the best 3 pt. percentage in the league hitting very close to 53% of his shots

                    Name                   Team   G    MP   FG3%   FGA
0       Domantas Sabonis         Indiana Pacers  74  24.8  0.529   9.5
1    Willie Cauley-Stein       Sacramento Kings  81  27.3  0.500   9.1
2             Joe Harris          Brooklyn Nets  76  30.2  0.474   9.8
3            Danny Green        Toronto Raptors  80  27.7  0.455   7.9
4          Stephen Curry  Golden State Warriors  69  33.8  0.437  19.4
..                   ...                    ...  ..   ...    ...   ...
203         Steven Adams  Oklahoma City Thunder  80  33.4  0.000  10.1
204         Clint Capela        Houston Rockets  67  33.6    NaN  10.9
205          Rudy Gobert              Utah Jazz  81  31.8    NaN   8.8
206       DeAndre Jordan        New York Knicks  69  29.7    NaN   6.5
207    Mitchell Robinson        New York Knicks  66  20.6    NaN   4.4

[208 rows x 6 columns]

# Who played the most minutes during the season

In [6]:
nba_data['Total Min Played'] = nba_data['G'] * nba_data['MP']
nba_data.sort_values('Total Min Played', ascending = False)[['Name', 'Team', 'G', 'MP', 'Total Min Played']]

#  Bradley Beal of the Washington Wizards played in all 82 games and averaged 36.9 minutes per game.  
#  This adds up to a total of 3,025.8 minutes played throughout the entire season

               Name                   Team   G    MP  Total Min Played
37     Bradley Beal     Washington Wizards  82  36.9            3025.8
202    James Harden        Houston Rockets  78  36.8            2870.4
486    Kemba Walker      Charlotte Hornets  82  34.9            2861.8
208   Tobias Harris     Philadelphia 76ers  82  34.7            2845.4
179     Paul George  Oklahoma City Thunder  77  36.9            2841.3
..              ...                    ...  ..   ...               ...
268  Terrence Jones        Houston Rockets   2   2.5               5.0
439   Jordan Sibert          Atlanta Hawks   1   4.0               4.0
192  Donte Grantham                    NaN   3   0.7               2.1
442    Kobi Simmons    Cleveland Cavaliers   1   2.0               2.0
405         Zhou Qi        Houston Rockets   1   1.0               1.0

[521 rows x 5 columns]

# What player given their player effiecency rating was the clutchest during the season?

In [7]:
clutchest_players = nba_data[(nba_data['G'] > 50) & (nba_data['MP'] > 20)].sort_values('PER', ascending = False)
clutchest_players

# Out of all of the players that played in atleast 50 games and played atleast an average of 20 minutes 
# per game, Giannis Antelokounmpo of the Milwaukee Bucks had the best player efficiency rating.  Close
# behind Giannis was James Harden of the Houston Rockets and Anthony Davis of the New Orleans Pelicans

,Name,Height,Weight,Team,Age,Salary,Points,Blocks,Steals,Assists,...,G,PER,OWS,DWS,WS,WS48,USG,BPM,VORP,Total Min Played
15,Giannis Antetokounmpo,83,242,Milwaukee Bucks,24,24157304,27.7,1.5,1.3,5.9,...,72,30.9,8.9,5.5,14.4,0.292,32.3,10.8,7.6,2361.6
202,James Harden,77,220,Houston Rockets,29,30431854,36.1,0.7,2.0,7.5,...,78,30.6,11.4,3.8,15.2,0.254,40.5,11.7,9.9,2870.4
123,Anthony Davis,82,253,New Orleans Pelicans,25,25434263,25.9,2.4,1.6,3.9,...,56,30.3,6.4,3.1,9.5,0.247,29.5,8.5,4.9,1848.0
264,Nikola Jokic,84,250,Denver Nuggets,23,24605181,20.1,0.7,1.4,7.3,...,80,26.3,7.5,4.3,11.8,0.226,27.4,9.5,7.3,2504.0
471,Karl-Anthony Towns,84,248,Minnesota Timberwolves,23,7839435,24.4,1.6,0.9,3.4,...,77,26.3,7.2,3.2,10.4,0.197,28.9,6.8,5.7,2548.7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
341,Darius Miller,80,225,New Orleans Pelicans,28,2205000,8.2,0.3,0.6,2.1,...,69,8.4,1.1,0.6,1.6,0.045,13.4,-1.7,0.1,1759.5
144,Jared Dudley,79,237,Brooklyn Nets,33,9530000,4.9,0.3,0.6,1.4,...,59,7.8,0.6,1.2,1.8,0.070,10.4,-0.7,0.4,1221.3
414,Austin Rivers,76,200,Phoenix Suns,26,12000000,8.1,0.3,0.6,2.2,...,76,7.7,0.4,0.8,1.2,0.028,14.5,-3.5,-0.7,2029.2
60,Avery Bradley,74,180,Memphis Grizzlies,28,12000000,9.9,0.3,0.7,2.4,...,63,7.6,-0.6,1.0,0.3,0.009,16.2,-2.8,-0.4,1902.6
162,Terrance Ferguson,79,190,Oklahoma City Thunder,20,2118840,6.9,0.2,0.5,1.0,...,74,6.4,1.2,1.6,2.8,0.070,10.6,-1.9,0.0,1931.4

# What team had the youngest roster?

In [8]:
youngest_roster = nba_data.groupby('Team', as_index = False)['Age'].mean()
youngest_roster.sort_values('Age', ascending = True)

# The Chicago Bulls had the youngest team with an average age of 24.31 years

                      Team        Age
4            Chicago Bulls  24.312500
25        Sacramento Kings  24.400000
21           Orlando Magic  24.533333
19         New York Knicks  24.625000
23            Phoenix Suns  24.761905
24  Portland Trail Blazers  24.857143
11          Indiana Pacers  25.058824
7           Denver Nuggets  25.266667
2            Brooklyn Nets  25.555556
1           Boston Celtics  25.600000
14       Memphis Grizzlies  25.647059
20   Oklahoma City Thunder  25.750000
18    New Orleans Pelicans  25.777778
5      Cleveland Cavaliers  26.000000
3        Charlotte Hornets  26.000000
8          Detroit Pistons  26.266667
22      Philadelphia 76ers  26.352941
0            Atlanta Hawks  26.476190
13      Los Angeles Lakers  26.625000
17  Minnesota Timberwolves  26.625000
29      Washington Wizards  26.764706
16         Milwaukee Bucks  26.928571
12    Los Angeles Clippers  27.105263
28               Utah Jazz  27.133333
27         Toronto Raptors  27.166667
9    Golden State Warriors  27.866667
6         Dallas Mavericks  27.866667
10         Houston Rockets  27.923077
26       San Antonio Spurs  28.133333
15              Miami Heat  28.181818

# Who is the highest paid player during the seasion?

In [69]:

nba_data.shape

highest_paid_dropped = nba_data.loc[nba_data['Salary'] != "-"]

#highest_paid_dropped.loc[highest_paid_dropped['Name'] == 'Stephen Curry']
#highest_paid_dropped


highest_paid_dropped_sorted = highest_paid_dropped.sort_values('Salary', kind = 'mergesort', ascending = True).reset_index()

highest_paid_dropped_sorted

# highest_paid_dropped_sorted = highest_paid_dropped.sort_values('Salary', kind = 'mergesort', ascending = True).reset_index()
# highest_paid_dropped_sorted
# nba_data.head(20)

,index,Name,Height,Weight,Team,Age,Salary,Points,Blocks,Steals,...,MP,G,PER,OWS,DWS,WS,WS48,USG,BPM,VORP
0,57,Isaac Bonga,80,180,Los Angeles Lakers,19,1000000,0.9,0.2,0.4,...,5.5,22,6.0,-0.3,0.2,-0.1,-0.059,15.7,-4.3,-0.1
1,313,Shelvin Mack,75,203,Orlando Magic,28,1000000,7.5,0.1,0.8,...,21.9,57,10.4,-0.2,1.1,0.9,0.034,18.1,-4.1,-0.7
2,107,Darren Collison,72,175,Indiana Pacers,31,10000000,11.2,0.1,1.4,...,28.2,76,16.7,3.9,2.9,6.8,0.153,17.7,1.2,1.8
3,193,Danny Green,78,215,Toronto Raptors,31,10000000,10.3,0.7,0.9,...,27.7,80,13.0,3.0,2.9,5.9,0.128,14.1,2.9,2.7
4,297,Jon Leuer,82,228,Detroit Pistons,29,10002681,3.8,0.1,0.3,...,9.8,41,13.2,0.4,0.5,0.9,0.110,16.1,-3.0,-0.1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
465,157,Dante Exum,78,190,Utah Jazz,23,9600000,6.9,0.1,0.3,...,15.8,42,11.2,0.2,0.7,1.0,0.069,21.3,-4.0,-0.3
466,129,Matthew Dellavedova,76,200,Cleveland Cavaliers,28,9607500,5.9,0.0,0.3,...,16.9,48,11.1,0.5,0.0,0.5,0.028,17.9,-5.5,-0.7
467,402,Dwight Powell,83,240,Dallas Mavericks,27,9631250,10.6,0.6,0.6,...,21.6,77,20.4,5.6,1.9,7.5,0.215,17.2,4.0,2.5
468,188,Devonte' Graham,74,185,Charlotte Hornets,23,988464,4.7,0.0,0.5,...,14.7,46,10.3,0.2,0.3,0.5,0.035,17.0,-4.3,-0.4
469,255,John Jenkins,76,215,Washington Wizards,27,99290,4.7,0.1,0.0,...,12.8,26,9.7,0.2,0.0,0.2,0.031,15.7,-5.2,-0.3

# At the end of a game, who WOULDN'T you want on the Free Throw Line?

In [77]:
worst_ft = nba_data[(nba_data['FTA'] > 1.8) & (nba_data['G'] > 50) & (nba_data['MP'] > 20)].sort_values('FT%')
worst_ft[['Name', 'Team', 'G', 'MP', 'FTA', 'FT%']]

# I narrowed the search to only include players that have over 1.8 FTA per game while playing in over 50 and 20 
# minutes per game.  These are all around the mean of each category and I wanted to make sure my sample size was
# large enough to determine the worst free throw shooter.  My conclusion is that Hassan Whiteside would be the player
# that I wouldn't want at the free throw line with the game on the line

                    Name                    Team   G    MP  FTA    FT%
499     Hassan Whiteside              Miami Heat  72  23.3  3.4  0.449
3           Steven Adams   Oklahoma City Thunder  80  33.4  3.7  0.500
94   Willie Cauley-Stein        Sacramento Kings  81  27.3  3.1  0.551
396        Mason Plumlee          Denver Nuggets  82  21.1  2.4  0.561
143       Andre Drummond         Detroit Pistons  79  33.5  5.2  0.590
..                   ...                     ...  ..   ...  ...    ...
409          J.J. Redick      Philadelphia 76ers  76  31.3  3.4  0.894
173     Danilo Gallinari    Los Angeles Clippers  68  30.3  6.0  0.904
299       Damian Lillard  Portland Trail Blazers  80  35.5  6.4  0.912
121        Stephen Curry   Golden State Warriors  69  33.8  4.2  0.916
67       Malcolm Brogdon         Milwaukee Bucks  64  28.6  2.4  0.928

[137 rows x 6 columns]